
application:
  name: ngx-uploader
  project: ngx-uploader
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: ngx-uploader
        paths:
          - /*
