
application:
  name: angular-example
  project: simple-test
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: angular-sample-app
        paths:
          - /*
